# Generated by Django 2.1.4 on 2018-12-17 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NIfTI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='series',
            name='nifti',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_dicom.NIfTI'),
        ),
    ]
