# Generated by Django 2.1.4 on 2019-03-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='modality',
            field=models.CharField(blank=True, choices=[('AR', 'Autorefraction'), ('ASMT', 'Content Assessment Results'), ('AU', 'Audio'), ('BDUS', 'Bone Densitometry (ultrasound)'), ('BMD', 'Bone Densitometry (X-Ray)'), ('BI', 'Biomagnetic imaging'), ('CR', 'Computed Radiography'), ('CT', 'Computed Tomography'), ('CTPROTOCOL', 'CT Protocol (Performed)'), ('DG', 'Diaphanography'), ('DOC', 'Document'), ('DX', 'Digital Radiography'), ('ECG', 'Electrocardiography'), ('EPS', 'Cardiac Electrophysiology'), ('EDS', 'Endoscopy'), ('FID', 'Fiducials'), ('GM', 'General Microscopy'), ('HC', 'Hard Copy'), ('HD', 'Hemodynamic Waveform'), ('IO', 'Intra-Oral Radiography'), ('IOL', 'Intraocular Lens Data'), ('IVOCT', 'Intravascular Optical Coherence Tomography'), ('IVUS', 'Intravascular Ultrasound'), ('KER', 'Keratometry'), ('KO', 'Key Object Selection'), ('LEN', 'Lensometry'), ('LS', 'Laser surface scan'), ('MG', 'Mammography'), ('MR', 'Magnetic Resonance'), ('M3D', 'Model for 3D Manufacturing'), ('NM', 'Nuclear Medicine'), ('OAM', 'Ophthalmic Axial Measurements'), ('OCT', 'Optical Coherence Tomography (non-Ophthalmic)'), ('OP', 'Ophthalmic Photography'), ('OPM', 'Ophthalmic Mapping'), ('OPT', 'Ophthalmic Tomography'), ('OPTBSV', 'Ophthalmic Tomography B-scan Volume Analysis'), ('OPTENF', 'Ophthalmic Tomography En Face'), ('OPV', 'Ophthalmic Visual Field'), ('OSS', 'Optical Surface Scan'), ('OT', 'Other'), ('PLAN', 'Plan'), ('PR', 'Presentation State'), ('PT', 'Positron emission tomography (PET)'), ('PX', 'Panoramic X-Ray'), ('REG', 'Registration'), ('RESP', 'Respiratory Waveform'), ('RF', 'Radio Fluoroscopy'), ('RG', 'Radiographic imaging (conventional film/screen)'), ('RTDOSE', 'Radiotherapy Dose'), ('RTIMAGE', 'Radiotherapy Image'), ('RTPLAN', 'Radiotherapy Plan'), ('RTRECORD', 'RT Treatment Record'), ('RTSTRUCT', 'Radiotherapy Structure Set'), ('RWV', 'Real World Value Map'), ('SEG', 'Segmentation'), ('SM', 'Slide Microscopy'), ('SMR', 'Stereometric Relationship'), ('SR', 'SR Document'), ('SRF', 'Subjective Refraction'), ('STAIN', 'Automated Slide Stainer'), ('TG', 'Thermography'), ('US', 'Ultrasound'), ('VA', 'Visual Acuity'), ('XA', 'X-Ray Angiography'), ('XC', 'External-camera Photography')], default='MR', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='mr_acquisition_type',
            field=models.CharField(blank=True, choices=[('2D', '2D'), ('3D', '3D')], default='2D', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='patient_position',
            field=models.CharField(blank=True, choices=[('HFP', 'Head First-Prone'), ('HFS', 'Head First-Supine'), ('HFDR', 'Head First-Decubitus Right'), ('HFDL', 'Head First-Decubitus Left'), ('FFDR', 'Feet First-Decubitus Right'), ('FFDL', 'Feet First-Decubitus Left'), ('FFP', 'Feet First-Prone'), ('FFS', 'Feet First-Supine'), ('LFP', 'Left First-Prone'), ('LFS', 'Left First-Supine'), ('RFP', 'Right First-Prone'), ('RFS', 'Right First-Supine'), ('AFDR', 'Anterior First-Decubitus Right'), ('AFDL', 'Anterior First-Decubitus Left'), ('PFDR', 'Posterior First-Decubitus Right'), ('PFDL', 'Posterior First-Decubitus Left')], default='HFS', max_length=4, null=True),
        ),
    ]
