# Generated by Django 2.2 on 2019-04-19 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='file',
            new_name='dcm',
        ),
    ]
