# Generated by Django 2.2 on 2019-04-22 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Image Number'),
        ),
        migrations.AlterField(
            model_name='image',
            name='uid',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)*$', code='invalid_uid', message='Digits and dots only!')], verbose_name='Image UID'),
        ),
    ]
