# Generated by Django 2.2 on 2019-04-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='study',
            name='comments',
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='uid',
            field=models.CharField(max_length=64, unique=True, verbose_name='Patient ID'),
        ),
    ]
