# Generated by Django 2.2 on 2019-05-31 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='slice_thickness',
            field=models.FloatField(blank=True, help_text='Nominal slice thickness, in millimeters.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
