# Generated by Django 2.1.7 on 2019-03-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='comments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
