# Generated by Django 2.2.8 on 2020-01-14 08:23

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0002_auto_20200114_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='pixel_spacing',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]), blank=True, help_text='Physical distance in the patient between the center of each pixel, specified by a numeric pair: adjacent row spacing (delimiter) adjacent column spacing in mm', null=True, size=2),
        ),
    ]
