# Generated by Django 2.2 on 2019-05-31 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0002_series_slice_thickness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='slice_thickness',
            field=models.FloatField(default=0, help_text='Nominal slice thickness, in millimeters.', validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
