# Generated by Django 2.1.7 on 2019-03-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0002_series_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ('number',), 'verbose_name_plural': 'Series'},
        ),
        migrations.AddField(
            model_name='patient',
            name='comments',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='comments',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='comments',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
