# Generated by Django 3.1 on 2020-12-13 07:06

from dicom_parser.header import Header as DicomHeader
from django.db import migrations, models


class Migration(migrations.Migration):
    def populate_new_fields(apps, schema_editor):
        Series = apps.get_model("django_dicom", "Series")
        for series in Series.objects.all():
            header = DicomHeader(str(series.image_set.first().dcm))
            series.pulse_sequence_name = header.get((0x0019, 0x109C))
            series.sequence_name = header.get((0x0018, 0x0024))
            series.save()

    dependencies = [
        ("django_dicom", "0002_auto_20201018_1638"),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="pulse_sequence_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the pulse sequence for annotation purposes. Potentially vendor-specific name.",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="sequence_name",
            field=models.CharField(
                blank=True,
                help_text="User defined name for the combination of Scanning Sequence and Sequence Variant.",
                max_length=64,
                null=True,
            ),
        ),
        migrations.RunPython(populate_new_fields),
    ]
