# Generated by Django 2.1.4 on 2019-02-04 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_study_image'),
        ('django_dicom', '0002_auto_20181217_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mri', to='research.Subject'),
        ),
    ]
