# Generated by Django 2.2 on 2019-04-22 13:45

from django.db import migrations, models
import django_dicom.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0002_auto_20190422_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='dcm',
            field=models.FileField(max_length=250, upload_to='dicom', validators=[django_dicom.models.validators.validate_file_extension]),
        ),
    ]
