# Generated by Django 2.1.7 on 2019-03-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0003_auto_20190326_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='comments',
        ),
        migrations.AlterField(
            model_name='nifti',
            name='path',
            field=models.FilePathField(max_length=500, unique=True),
        ),
    ]
