# Generated by Django 2.2.8 on 2020-02-02 06:58

from django.db import migrations, models
import django_dicom.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0003_auto_20200114_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='dcm',
            field=models.FileField(max_length=1000, upload_to='dicom', validators=[django_dicom.models.validators.validate_file_extension]),
        ),
    ]
