# Generated by Django 2.1.4 on 2019-02-05 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0003_patient_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='series', to='django_dicom.Patient'),
        ),
        migrations.AlterField(
            model_name='series',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='series', to='django_dicom.Study'),
        ),
    ]
