# Generated by Django 2.2 on 2019-06-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0003_auto_20190531_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='operators_name',
            field=models.CharField(blank=True, help_text='Name(s) of the operator(s) supporting the Series.', max_length=64, null=True),
        ),
    ]
