# Generated by Django 2.1.5 on 2019-02-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0004_auto_20190205_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='echo_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='inversion_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
