# Generated by Django 2.2.8 on 2020-03-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0004_auto_20200202_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='warning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
