# Generated by Django 2.1.7 on 2019-03-30 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0004_auto_20190330_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='_nifti',
        ),
        migrations.DeleteModel(
            name='NIfTI',
        ),
    ]
