# Generated by Django 2.2 on 2019-06-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0004_series_operators_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='echo_train_length',
            field=models.PositiveIntegerField(blank=True, help_text='Number of lines in k-space acquired per excitation per image.', null=True),
        ),
    ]
