# Generated by Django 2.2 on 2019-06-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("django_dicom", "0005_series_echo_train_length")]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="uid",
            field=models.CharField(
                max_length=64, unique=True, verbose_name="Patient UID"
            ),
        )
    ]
