# Generated by Django 2.2.8 on 2020-03-17 06:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0005_image_warning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='warning',
        ),
        migrations.AddField(
            model_name='image',
            name='warnings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=None, size=None),
            preserve_default=False,
        ),
    ]
