# Generated by Django 2.1.5 on 2019-02-10 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0005_auto_20190210_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='echo_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='inversion_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='django_dicom.Patient'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='django_dicom.Series'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='django_dicom.Study'),
        ),
    ]
