# Generated by Django 2.2 on 2019-04-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0005_auto_20190422_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='number',
            field=models.IntegerField(verbose_name='Image Number'),
        ),
        migrations.AlterField(
            model_name='image',
            name='time',
            field=models.TimeField(),
        ),
    ]
