# Generated by Django 2.2 on 2019-06-27 08:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("django_dicom", "0006_auto_20190627_0757")]

    operations = [
        migrations.AlterField(
            model_name="series",
            name="slice_thickness",
            field=models.FloatField(
                blank=True,
                help_text="Nominal slice thickness, in millimeters.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        )
    ]
