# Generated by Django 3.2.6 on 2021-10-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_dicom", "0006_alter_storageserviceclassprovider_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="sequence_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Anatomical",
                        (
                            ("localizer", "Localizer"),
                            ("flair", "FLAIR"),
                            ("ir_epi", "IR-EPI"),
                            ("mprage", "MPRAGE"),
                            ("t2w", "T2-weighted"),
                        ),
                    ),
                    (
                        "Diffusion",
                        (("dwi", "DWI"), ("dwi_fieldmap", "DWI Fieldmap")),
                    ),
                    (
                        "Functional",
                        (
                            ("bold", "fMRI"),
                            ("func_fieldmap", "fMRI Fieldmap"),
                            ("func_sbref", "fMRI SBRef"),
                        ),
                    ),
                    (None, "Unknown"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
