# Generated by Django 2.1.5 on 2019-02-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0006_auto_20190210_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='repetition_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
