# Generated by Django 2.1.5 on 2019-02-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0007_series_repetition_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='echo_time',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='inversion_time',
        ),
    ]
