# Generated by Django 2.1.5 on 2019-02-11 16:02

import django.core.validators
from django.db import migrations, models
import django_dicom.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0008_auto_20190211_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='scanning_sequence',
            field=django_dicom.models.fields.ChoiceArrayField(base_field=models.CharField(choices=[('SE', 'Spin Echo'), ('IR', 'Inversion Recovery'), ('EP', 'Echo Planar'), ('RM', 'Research Mode')], max_length=2), blank=True, null=True, size=5),
        ),
        migrations.AlterField(
            model_name='series',
            name='echo_time',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='series',
            name='inversion_time',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='series',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Series Number'),
        ),
        migrations.AlterField(
            model_name='series',
            name='repetition_time',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
