# Generated by Django 2.2.8 on 2020-03-17 11:38

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0008_auto_20200317_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataElementDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), blank=True, null=True, size=2)),
                ('keyword', models.CharField(max_length=255)),
                ('value_representation', models.CharField(choices=[('AE', 'Application Entity'), ('AS', 'Age String'), ('AT', 'Attribute Tag'), ('CS', 'Code String'), ('DA', 'Date'), ('DS', 'Decimal String'), ('DT', 'Date Time'), ('FL', 'Floating Point Single'), ('FD', 'Floating Point Double'), ('IS', 'Integer String'), ('LO', 'Long String'), ('LT', 'Long Text'), ('OB', 'Other Byte'), ('OD', 'Other Double'), ('OF', 'Other Float'), ('OL', 'Other Long'), ('OV', 'Other 64-bit Very Long'), ('OW', 'Other Word'), ('PN', 'Person Name'), ('SH', 'Short String'), ('SL', 'Signed Long'), ('SQ', 'Sequence of Items'), ('SS', 'Signed Short'), ('ST', 'Short Text'), ('SV', 'Signed 64-bit Very Long'), ('TM', 'Time'), ('UC', 'Unlimited Characters'), ('UI', 'Unique Identifer'), ('UL', 'Unsigned Long'), ('UN', 'Unknown'), ('UR', 'Universal Resource'), ('US', 'Unsigned Short'), ('UT', 'Unlimited Text'), ('UV', 'Unsigned 64-bit Very Long')], max_length=2)),
                ('value_multiplicity', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-id',)},
        ),
        migrations.CreateModel(
            name='DataElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning', models.TextField(blank=True, null=True)),
                ('_value', django.contrib.postgres.fields.jsonb.JSONField()),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_dicom.DataElementDefinition')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_dicom.Image')),
            ],
            options={
                'unique_together': {('image', 'definition')},
            },
        ),
    ]
