# Generated by Django 2.2.8 on 2020-03-18 06:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0009_auto_20200317_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Image Number'),
        ),
        migrations.AlterField(
            model_name='image',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_dicom.Series'),
        ),
        migrations.AlterField(
            model_name='image',
            name='warnings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='series',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_dicom.Study'),
        ),
    ]
