# Generated by Django 2.2.8 on 2020-03-18 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0010_auto_20200318_0610'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataElementValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dataelement',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataelement',
            name='_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_dicom.DataElementValue'),
        ),
        migrations.AlterField(
            model_name='dataelement',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_element_set', to='django_dicom.Image'),
        ),
    ]
