# Generated by Django 2.1.5 on 2019-02-12 13:55

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0010_series_slice_timing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='slice_timing',
        ),
        migrations.AddField(
            model_name='instance',
            name='slice_timing',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]), blank=True, null=True, size=None),
        ),
    ]
