# Generated by Django 2.2.8 on 2020-03-19 05:26

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0011_auto_20200318_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeString',
            fields=[
                ('dataelementvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dicom.DataElementValue')),
                ('value', models.FloatField(verbose_name='Age in years')),
                ('raw', models.CharField(max_length=4)),
            ],
            bases=('django_dicom.dataelementvalue',),
        ),
        migrations.CreateModel(
            name='ApplicationEntity',
            fields=[
                ('dataelementvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dicom.DataElementValue')),
                ('value', models.CharField(max_length=16)),
                ('raw', models.CharField(max_length=16)),
            ],
            bases=('django_dicom.dataelementvalue',),
        ),
        migrations.CreateModel(
            name='CodeString',
            fields=[
                ('dataelementvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dicom.DataElementValue')),
                ('value', models.CharField(max_length=16)),
                ('raw', models.CharField(max_length=16)),
            ],
            bases=('django_dicom.dataelementvalue',),
        ),
        migrations.CreateModel(
            name='DecimalString',
            fields=[
                ('dataelementvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dicom.DataElementValue')),
                ('value', models.FloatField()),
                ('raw', models.CharField(max_length=16)),
            ],
            bases=('django_dicom.dataelementvalue',),
        ),
        migrations.CreateModel(
            name='FloatingPointDouble',
            fields=[
                ('dataelementvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dicom.DataElementValue')),
                ('value', models.FloatField()),
                ('raw', models.BinaryField(max_length=64)),
            ],
            bases=('django_dicom.dataelementvalue',),
        ),
        migrations.CreateModel(
            name='FloatingPointSingle',
            fields=[
                ('dataelementvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dicom.DataElementValue')),
                ('value', models.FloatField()),
                ('raw', models.BinaryField(max_length=32)),
            ],
            bases=('django_dicom.dataelementvalue',),
        ),
        migrations.CreateModel(
            name='IntegerString',
            fields=[
                ('dataelementvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dicom.DataElementValue')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(-2147483648), django.core.validators.MaxValueValidator(2147483647)])),
                ('raw', models.CharField(max_length=12)),
            ],
            bases=('django_dicom.dataelementvalue',),
        ),
        migrations.CreateModel(
            name='LongString',
            fields=[
                ('dataelementvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dicom.DataElementValue')),
                ('value', models.CharField(max_length=64)),
                ('raw', models.CharField(max_length=64)),
            ],
            bases=('django_dicom.dataelementvalue',),
        ),
        migrations.CreateModel(
            name='PersonName',
            fields=[
                ('dataelementvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dicom.DataElementValue')),
                ('value', django.contrib.postgres.fields.jsonb.JSONField()),
                ('raw', models.CharField(max_length=64)),
            ],
            bases=('django_dicom.dataelementvalue',),
        ),
        migrations.CreateModel(
            name='SequenceOfItems',
            fields=[
                ('dataelementvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dicom.DataElementValue')),
            ],
            bases=('django_dicom.dataelementvalue',),
        ),
        migrations.CreateModel(
            name='ShortString',
            fields=[
                ('dataelementvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dicom.DataElementValue')),
                ('value', models.CharField(max_length=16)),
                ('raw', models.CharField(max_length=16)),
            ],
            bases=('django_dicom.dataelementvalue',),
        ),
        migrations.CreateModel(
            name='ShortText',
            fields=[
                ('dataelementvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dicom.DataElementValue')),
                ('value', models.CharField(max_length=1024)),
                ('raw', models.CharField(max_length=1024)),
            ],
            bases=('django_dicom.dataelementvalue',),
        ),
        migrations.CreateModel(
            name='UniqueIdentifier',
            fields=[
                ('dataelementvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dicom.DataElementValue')),
                ('value', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)*$', code='invalid_uid', message='Digits and dots only!')])),
                ('raw', models.CharField(max_length=64)),
            ],
            bases=('django_dicom.dataelementvalue',),
        ),
        migrations.CreateModel(
            name='Unknown',
            fields=[
                ('dataelementvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dicom.DataElementValue')),
                ('value', models.TextField()),
                ('raw', models.TextField()),
            ],
            bases=('django_dicom.dataelementvalue',),
        ),
        migrations.CreateModel(
            name='UnlimitedText',
            fields=[
                ('dataelementvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dicom.DataElementValue')),
                ('value', models.TextField()),
                ('raw', models.TextField()),
            ],
            bases=('django_dicom.dataelementvalue',),
        ),
        migrations.RemoveField(
            model_name='dataelement',
            name='warning',
        ),
        migrations.AddField(
            model_name='dataelement',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='django_dicom.DataElementValue'),
        ),
    ]
