# Generated by Django 2.1.5 on 2019-02-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0012_remove_instance_slice_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='b_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
