# Generated by Django 2.2.8 on 2020-03-19 05:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0012_auto_20200319_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataelementvalue',
            name='warning',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
