# Generated by Django 2.1.5 on 2019-02-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0013_instance_b_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
