# Generated by Django 2.2.8 on 2020-03-19 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0013_auto_20200319_0542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataelementvalue',
            old_name='warning',
            new_name='warnings',
        ),
    ]
