# Generated by Django 2.2.8 on 2020-03-19 06:02

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0014_auto_20200319_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agestring',
            name='raw',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='agestring',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Age in years'),
        ),
        migrations.AlterField(
            model_name='applicationentity',
            name='raw',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='applicationentity',
            name='value',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='codestring',
            name='raw',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='codestring',
            name='value',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='decimalstring',
            name='raw',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='decimalstring',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='floatingpointdouble',
            name='raw',
            field=models.BinaryField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='floatingpointdouble',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='floatingpointsingle',
            name='raw',
            field=models.BinaryField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='floatingpointsingle',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='integerstring',
            name='raw',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='integerstring',
            name='value',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-2147483648), django.core.validators.MaxValueValidator(2147483647)]),
        ),
        migrations.AlterField(
            model_name='longstring',
            name='raw',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='longstring',
            name='value',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='personname',
            name='raw',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='personname',
            name='value',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shortstring',
            name='raw',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='shortstring',
            name='value',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='shorttext',
            name='raw',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='shorttext',
            name='value',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='uniqueidentifier',
            name='raw',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='uniqueidentifier',
            name='value',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)*$', code='invalid_uid', message='Digits and dots only!')]),
        ),
        migrations.AlterField(
            model_name='unknown',
            name='raw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unknown',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unlimitedtext',
            name='raw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unlimitedtext',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
