# Generated by Django 2.2.8 on 2020-03-19 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0015_auto_20200319_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('dataelementvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dicom.DataElementValue')),
                ('value', models.DateField()),
                ('raw', models.CharField(help_text='YYYYMMDD', max_length=8)),
            ],
            bases=('django_dicom.dataelementvalue',),
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('dataelementvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dicom.DataElementValue')),
                ('value', models.TimeField()),
                ('raw', models.CharField(help_text='HHMMSS.FFFFFF', max_length=16)),
            ],
            bases=('django_dicom.dataelementvalue',),
        ),
    ]
