# Generated by Django 2.1.4 on 2019-02-13 19:15

import django.core.validators
from django.db import migrations, models
import django_dicom.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0015_series_modality'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='body_part_examined',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='device_serial_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='magnetic_field_strength',
            field=models.FloatField(default=3, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='manufacturers_model_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='mr_acquisition_type',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D')], default='2D', max_length=2),
        ),
        migrations.AddField(
            model_name='series',
            name='patient_position',
            field=models.CharField(choices=[('HFP', 'Head First-Prone'), ('HFS', 'Head First-Supine'), ('HFDR', 'Head First-Decubitus Right'), ('HFDL', 'Head First-Decubitus Left'), ('FFDR', 'Feet First-Decubitus Right'), ('FFDL', 'Feet First-Decubitus Left'), ('FFP', 'Feet First-Prone'), ('FFS', 'Feet First-Supine'), ('LFP', 'Left First-Prone'), ('LFS', 'Left First-Supine'), ('RFP', 'Right First-Prone'), ('RFS', 'Right First-Supine'), ('AFDR', 'Anterior First-Decubitus Right'), ('AFDL', 'Anterior First-Decubitus Left'), ('PFDR', 'Posterior First-Decubitus Right'), ('PFDL', 'Posterior First-Decubitus Left')], default='HFS', max_length=4),
        ),
        migrations.AddField(
            model_name='series',
            name='sequence_variant',
            field=django_dicom.models.fields.ChoiceArrayField(base_field=models.CharField(choices=[('SK', 'Segmented k-space'), ('MTC', 'Magnetization Transfer Contrast'), ('SS', 'Steady State'), ('TRSS', 'Time Reversed Steady State'), ('SP', 'Spoiled'), ('MP', 'MAG Prepared'), ('OSP', 'Oversampling Phase'), ('NONE', 'None')], max_length=4), blank=True, null=True, size=None),
        ),
    ]
