# Generated by Django 2.2.8 on 2020-03-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0016_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floatingpointdouble',
            name='raw',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='floatingpointsingle',
            name='raw',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
