# Generated by Django 2.2.8 on 2020-03-19 08:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0017_auto_20200319_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedLong',
            fields=[
                ('dataelementvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dicom.DataElementValue')),
                ('value', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2147483647), django.core.validators.MinValueValidator(-2147483648)])),
                ('raw', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2147483647), django.core.validators.MinValueValidator(-2147483648)])),
            ],
            bases=('django_dicom.dataelementvalue',),
        ),
        migrations.CreateModel(
            name='SignedShort',
            fields=[
                ('dataelementvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dicom.DataElementValue')),
                ('value', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(32767), django.core.validators.MinValueValidator(-32768)])),
                ('raw', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(32767), django.core.validators.MinValueValidator(-32768)])),
            ],
            bases=('django_dicom.dataelementvalue',),
        ),
        migrations.CreateModel(
            name='UnsignedLong',
            fields=[
                ('dataelementvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dicom.DataElementValue')),
                ('value', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4294967296)])),
                ('raw', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4294967296)])),
            ],
            bases=('django_dicom.dataelementvalue',),
        ),
        migrations.CreateModel(
            name='UnsignedShort',
            fields=[
                ('dataelementvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dicom.DataElementValue')),
                ('value', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(65536)])),
                ('raw', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(65536)])),
            ],
            bases=('django_dicom.dataelementvalue',),
        ),
        migrations.AddField(
            model_name='dataelementvalue',
            name='data_element',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='django_dicom.DataElement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataelementvalue',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
