# Generated by Django 2.2.8 on 2020-03-19 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0018_auto_20200319_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataelement',
            name='_value',
        ),
    ]
