# Generated by Django 2.2.8 on 2020-03-19 13:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0019_remove_dataelement__value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataelementvalue',
            name='data_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_value', to='django_dicom.DataElement'),
        ),
        migrations.AlterField(
            model_name='uniqueidentifier',
            name='value',
            field=models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)*$', code='invalid_uid', message='Digits and dots only!')]),
        ),
    ]
