# Generated by Django 2.1.4 on 2019-02-14 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0019_auto_20190214_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mri_patient_set', to='research.Subject'),
        ),
        migrations.AlterField(
            model_name='series',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_dicom.Patient'),
        ),
        migrations.AlterField(
            model_name='series',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_dicom.Study'),
        ),
    ]
