# Generated by Django 2.1.5 on 2019-02-19 13:51

from django.db import migrations, models
import django_dicom.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0020_auto_20190214_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=6),
        ),
        migrations.AlterField(
            model_name='series',
            name='date',
            field=models.DateField(help_text='Date the Series started.'),
        ),
        migrations.AlterField(
            model_name='series',
            name='sequence_variant',
            field=django_dicom.models.fields.ChoiceArrayField(base_field=models.CharField(choices=[('SK', 'Segmented k-space'), ('MTC', 'Magnetization Transfer Contrast'), ('SS', 'Steady State'), ('TRSS', 'Time Reversed Steady State'), ('SP', 'Spoiled'), ('MP', 'MAG Prepared'), ('OSP', 'Oversampling Phase'), ('NONE', 'None')], max_length=4), blank=True, help_text='Variant of the Scanning Sequence.', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='series',
            name='time',
            field=models.TimeField(help_text='Time the Series started.'),
        ),
    ]
