# Generated by Django 2.2.8 on 2020-03-21 10:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0020_auto_20200319_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_dicom.Header')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dataelement',
            name='header',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='data_element_set', to='django_dicom.Header'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='header',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='django_dicom.Header'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='dataelement',
            unique_together={('header', 'definition')},
        ),
        migrations.RemoveField(
            model_name='dataelement',
            name='image',
        ),
    ]
