# Generated by Django 2.2.8 on 2020-03-21 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0021_auto_20200321_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataelement',
            name='index',
        ),
        migrations.RemoveField(
            model_name='dataelement',
            name='parent',
        ),
        migrations.AddField(
            model_name='header',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_dicom.SequenceOfItems'),
        ),
    ]
