# Generated by Django 2.1.5 on 2019-03-11 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0022_auto_20190307_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='flip_angle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='institution_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='protocol_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='sequence_name',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='magnetic_field_strength',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
