# Generated by Django 2.2.8 on 2020-03-21 11:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0022_auto_20200321_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsaHeader',
            fields=[
                ('dataelementvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dicom.DataElementValue')),
                ('raw', models.TextField(blank=True, null=True)),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            bases=('django_dicom.dataelementvalue',),
        ),
    ]
