# Generated by Django 2.2.8 on 2020-03-21 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0023_csaheader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='header',
        ),
        migrations.AddField(
            model_name='header',
            name='image',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='_header', to='django_dicom.Image'),
            preserve_default=False,
        ),
    ]
