# Generated by Django 2.2.8 on 2020-03-21 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0024_auto_20200321_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='header',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='django_dicom.Header'),
            preserve_default=False,
        ),
    ]
