# Generated by Django 2.1.4 on 2019-03-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0024_auto_20190311_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instance',
            old_name='uploaded_at',
            new_name='created_at',
        ),
    ]
