# Generated by Django 2.2.8 on 2020-03-24 13:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0026_auto_20200324_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='operators_name',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Name(s) of the operator(s) supporting the Series.', null=True),
        ),
    ]
