# Generated by Django 2.1.4 on 2019-03-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0026_auto_20190312_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='date',
            field=models.DateField(blank=True, help_text='Date the Series started.', null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='time',
            field=models.TimeField(blank=True, help_text='Time the Series started.', null=True),
        ),
    ]
