# Generated by Django 2.2.8 on 2020-03-25 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0027_auto_20200324_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongText',
            fields=[
                ('dataelementvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dicom.DataElementValue')),
                ('value', models.TextField(blank=True, null=True)),
                ('raw', models.TextField(blank=True, null=True)),
            ],
            bases=('django_dicom.dataelementvalue',),
        ),
    ]
