# Generated by Django 2.2.8 on 2020-03-25 08:39

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0028_longtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherWord',
            fields=[
                ('dataelementvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dicom.DataElementValue')),
                ('value', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('raw', models.BinaryField(blank=True, null=True)),
            ],
            bases=('django_dicom.dataelementvalue',),
        ),
    ]
