# Generated by Django 2.1.5 on 2019-03-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0028_auto_20190313_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='sequence_name',
        ),
        migrations.AddIndex(
            model_name='instance',
            index=models.Index(fields=['instance_uid'], name='django_dico_instanc_912612_idx'),
        ),
        migrations.AddIndex(
            model_name='instance',
            index=models.Index(fields=['date', 'time'], name='django_dico_date_e1bad8_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['patient_id'], name='django_dico_patient_2ebf71_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['date_of_birth'], name='django_dico_date_of_49f161_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['series_uid'], name='django_dico_series__1e48d6_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['date', 'time'], name='django_dico_date_c6f151_idx'),
        ),
        migrations.AddIndex(
            model_name='study',
            index=models.Index(fields=['study_uid'], name='django_dico_study_u_a6544a_idx'),
        ),
    ]
