# Generated by Django 2.2.8 on 2020-03-26 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0029_otherword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataelementvalue',
            name='data_element',
        ),
        migrations.AddField(
            model_name='dataelement',
            name='_values',
            field=models.ManyToManyField(related_name='data_element_set', to='django_dicom.DataElementValue'),
        ),
        migrations.AlterField(
            model_name='dataelement',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_element_set', to='django_dicom.DataElementDefinition'),
        ),
    ]
