# Generated by Django 2.1.5 on 2019-03-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0029_auto_20190313_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='b_value',
        ),
    ]
