# Generated by Django 2.2.8 on 2020-03-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0030_auto_20200326_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataelementvalue',
            name='warnings',
        ),
        migrations.AddField(
            model_name='dataelementvalue',
            name='warning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
