# Generated by Django 2.2.8 on 2020-04-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0031_auto_20200329_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataelement',
            options={'ordering': ('definition',)},
        ),
        migrations.AlterModelOptions(
            name='dataelementvalue',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ('-date', 'time', 'number'), 'verbose_name_plural': 'Series'},
        ),
        migrations.AddIndex(
            model_name='dataelement',
            index=models.Index(fields=['header', 'definition'], name='django_dico_header__b64ee8_idx'),
        ),
    ]
