# Generated by Django 2.2.8 on 2020-04-01 04:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0032_auto_20200401_0407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataelementdefinition',
            options={'ordering': ('keyword',)},
        ),
        migrations.AlterField(
            model_name='dataelementdefinition',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataelementdefinition',
            name='tag',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), default=None, size=2, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='dataelementdefinition',
            index=models.Index(fields=['keyword'], name='django_dico_keyword_08498b_idx'),
        ),
    ]
