# Generated by Django 2.2.8 on 2020-04-01 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0033_auto_20200401_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataelementdefinition',
            name='value_multiplicity',
        ),
    ]
