# Generated by Django 2.2.8 on 2020-04-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0035_auto_20200403_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='raw',
            field=models.CharField(blank=True, help_text='YYYYMMDD', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='value',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='raw',
            field=models.CharField(blank=True, help_text='HHMMSS.FFFFFF', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='value',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
