# Generated by Django 2.2.8 on 2020-04-09 06:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0036_auto_20200403_0456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataelementvalue',
            name='warning',
        ),
        migrations.AddField(
            model_name='dataelementvalue',
            name='warnings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
