# Generated by Django 2.2.12 on 2020-04-15 04:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dicom', '0038_auto_20200411_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataelementdefinition',
            name='tag',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), size=2),
        ),
        migrations.AlterUniqueTogether(
            name='dataelementdefinition',
            unique_together={('tag', 'keyword')},
        ),
    ]
