name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      DB_NAME: test_db
      DB_USER: test_user
      DB_PASSWORD: password
    
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0   
      with:
        postgresql db: test_db
        postgresql user: test_user
        postgresql password: password        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        coverage run run_tests.py
    - name: Upload coverage report to codecov.io
      uses: codecov/codecov-action@v3.1.1        
